// <auto-generated />
using Don_SampleTrackingApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DonSampleTrackingApp.Migrations
{
    [DbContext(typeof(RaportareDbContext))]
    partial class RaportareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Don_SampleTrackingApp.ProbaModel", b =>
                {
                    b.Property<int>("ProbaModelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calitate");

                    b.Property<string>("DataPrelevare")
                        .HasMaxLength(100);

                    b.Property<string>("DataPreluare");

                    b.Property<string>("DataRaspunsCalitate");

                    b.Property<int>("Diametru");

                    b.Property<int>("DuritateHB");

                    b.Property<int>("KV1");

                    b.Property<int>("KV2");

                    b.Property<int>("KV3");

                    b.Property<int>("NumarCuptor");

                    b.Property<string>("NumeUtilizatorCalitate");

                    b.Property<string>("ObservatiiCalitate");

                    b.Property<string>("ObservatiiOperator");

                    b.Property<int>("RezultatProba");

                    b.Property<string>("Sarja");

                    b.Property<string>("SiglaFurnizor");

                    b.Property<int>("Temperatura");

                    b.Property<int>("TipCapBara");

                    b.Property<int>("TipTratamentTermic");

                    b.Property<int>("Tipproba");

                    b.Property<string>("UserName");

                    b.HasKey("ProbaModelId");

                    b.ToTable("ProbaModels");
                });

            modelBuilder.Entity("Don_SampleTrackingApp.TrackingUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Nume")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .HasMaxLength(100);

                    b.Property<string>("Prenume")
                        .HasMaxLength(100);

                    b.Property<int>("Rol");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
